set nocompatible              " be iMproved, required
filetype off                  " required

"git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

"" vim is killed by accident? use fg to call it back

"

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" latex support
Plugin 'lervag/vimtex'

" The following are examples of different formats supported.
" auto commenter 
Plugin 'scrooloose/nerdcommenter'

" auto completion
" see install.sh
" to add compiler flags use the CMAKE_EXPORT_COMPILE_COMMANDS
Plugin 'Valloric/YouCompleteMe'

" fugitive is a tool for Git and Github
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'

Plugin 'a.vim'

" command-t is for fast file lookup, type \t to trigger
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'

" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" spark up is a html-helping script
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

"" install universal-ctags instead of old ctags
Plugin 'majutsushi/tagbar'

" theme related
Plugin 'altercation/vim-colors-solarized'

" minibuf 
" use :b 1 :b2 to switch between buff
" Plugin 'fholgado/minibufexpl.vim'

" nerdtree 
" for IDE-like file navigation
Plugin 'scrooloose/nerdtree'

"vimoutliner for note taking
Plugin 'vimoutliner/vimoutliner'
" default is set into ',,'
" :help votl_cheatsheet for quick check
"Plugin 'vim-scripts/cscope.vim'

" See
" https://powerline.readthedocs.io/en/master/installation/linux.html#fonts-installation
" for fonts installation
Bundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}

" python syntax check
" press F7 to check
Plugin 'nvie/vim-flake8'

"" linter
Plugin 'w0rp/ale'


" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
"Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
" ycm
" let g:ycm_global_ycm_extra_conf='~/.ycm_extra_conf.py'

" default split position
set splitbelow
set splitright

" spell check
set spelllang=en
set spellfile=$HOME/Dropbox/Contents/vim/spell/en.utf-4.add
highlight SpellBad ctermfg=009 ctermbg=011 guifg=#ff0000 guibg=#ffff00


" It might use large amount of memory due to the tags:
"   https://github.com/Valloric/YouCompleteMe/issues/595
let g:ycm_server_use_vim_stdout = 1
let g:ycm_server_log_level = 'debug'

" ale default, use :echo g: gle_c.. to check
" ALEInfo
let g:ale_c_parse_compile_commands = 1
" let g:ale_completion_enabled = 1



filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"

" For Taglist"
" use ctags -R to generate tags
" F9 will trigger taglist
"
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
"use F9 to open taglist only
map <silent> <F9> :TlistToggle<cr>


" add the tagbar support
nmap <F8> :TagbarToggle<CR>
map <C-n> :NERDTreeToggle<CR>

" use Grep to search string
" grep -nR "something"

syntax on
" set background=dark
" colorscheme solarized

set cursorline
"
""always uses spaces instead of tab characters
set expandtab
" size of an "indent"
set tabstop=2
set shiftwidth=2

""
set encoding=utf-8

" set tags=; cs add in the .vimlocal file of project root
silent! so .vimlocal

""set hi Search cterm=NONE ctermfg=white ctermbg=blue
hi Search ctermfg=grey ctermbg=black

" file template
" see https://shapeshed.com/vim-templates/ for more info
" also http://vim.wikia.com/wiki/Auto_commands_for_C/C%2B%2B_editing
if has("autocmd")
  augroup templates
    autocmd BufNewFile *.sh 0r ~/configurations/vim/templates/skeleton.sh
    "autocmd BufWritePre,FileWritePre *.sh   ks|call LastMod()|'s

    autocmd BufNewFile *.cc 0r ~/configurations/vim/templates/skeleton.c
    "autocmd BufWritePre,FileWritePre *.cc   ks|call LastMod()|'s
    autocmd BufNewFile *.cc 0r ~/configurations/vim/templates/skeleton.c

    autocmd BufNewFile *.cpp 0r ~/configurations/vim/templates/skeleton.c
    "autocmd BufWritePre,FileWritePre *.h   ks|call LastMod()|'s

    autocmd BufNewFile *.h 0r ~/configurations/vim/templates/skeleton.c |ks |call append(line('$'), IncludeGuard())|'s
    autocmd BufNewFile *.hpp 0r ~/configurations/vim/templates/skeleton.c |ks |call append(line('$'), IncludeGuard())|'s
    "autocmd BufWritePre,FileWritePre *.c   ks|call LastMod()|'s

    autocmd BufNewFile CHANGELOG* 0r ~/configurations/vim/templates/skeleton.CHANGELOG.md |ks|'s
   "  autocmd BufReadPost,BufNewFile  CHANGELOG* ks|call append(8, NewLog())|'s

	function! FileName()
	   return expand('%:t')
	endfunction
	function! HeadName()
	   return toupper(substitute(FileName(), '\.', "_", "g"))
	endfunction
	function! IncludeGuard()
	   let lines = []
	   let lines +=  ["#ifndef " . HeadName() . "_"]
	   let lines +=  ["#define " . HeadName() . "_"]
	   let lines +=  ["#ifdef __cplusplus"]
     let lines +=  ["extern \"C\" {"]
     let lines +=  ["#endif"]
	   let lines +=  [""]
     let lines +=  ["#ifdef __cplusplus"]
     let lines +=  ["}"]
     let lines +=  ["#endif"]
	   let lines +=  ["#endif"]
	   return lines
	endfunction
"autocmd BufNewFile *.h  call append(0, IncludeGuard())
"
  augroup END

  " older version of vim doesn't recoganize md as markdown
  augroup markdown

    " remove previous autocmds
    autocmd!

    " set every new or read *.md buffer to use the markdown filetype
    au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

  augroup END

  augroup clangtools
  " lang-format -style=google -dump-config > .clang-format
    autocmd!

		function! Formatonsave()
			let l:formatdiff = 1
      py3f /usr/share/clang/clang-format-6.0/clang-format.py
		endfunction

		autocmd BufWritePre *.h,*.cc,*.cpp,*.hpp call Formatonsave()

  augroup END

endif


augroup resCur
	autocmd!
        autocmd BufReadPost * call setpos(".", getpos("'\""))
augroup END

" this makes vim look better! from https://unix.stackexchange.com/a/88880
color desert

" trailing space
match Error /\s\+$/
