set nocompatible              " be iMproved, required
filetype off                  " required

"git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

"" vim is killed by accident? use fg to call it back

"

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" latex support
Plugin 'lervag/vimtex'

"" c++ hightlight
"" this require lua support for vim, install vim-gnome
Plugin 'jeaye/color_coded'

" The following are examples of different formats supported.
" auto commenter
Plugin 'scrooloose/nerdcommenter'
" auto completion
" ./install.py --clang-completer --system-libclang
" to add compiler flags use the CMAKE_EXPORT_COMPILE_COMMANDS
Plugin 'Valloric/YouCompleteMe'

" fugitive is a tool for Git and Github
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'

Plugin 'a.vim'

" plugin
Plugin 'taglist.vim'

" command-t is for fast file lookup, type \t to trigger
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'

" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" spark up is a html-helping script
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

""
Plugin 'majutsushi/tagbar'

" theme related
Plugin 'altercation/vim-colors-solarized'

" minibuf 
" use :b 1 :b2 to switch between buff
Plugin 'fholgado/minibufexpl.vim'

" nerdtree 
" for IDE-like file navigation
Plugin 'scrooloose/nerdtree'

"vimoutliner for note taking
Plugin 'vimoutliner/vimoutliner'
" default is set into ',,'
" :help votl_cheatsheet for quick check
"Plugin 'vim-scripts/cscope.vim'


" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
"Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
" ycm
" let g:ycm_global_ycm_extra_conf='~/.ycm_extra_conf.py'

" spell check
set spelllang=en
set spellfile=$HOME/Dropbox/Contents/vim/spell/en.utf-4.add


filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"

" For Taglist"
" use ctags -R to generate tags
" F9 will trigger taglist
"
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
"use F9 to open taglist only
map <silent> <F9> :TlistToggle<cr>


" add the tagbar support
nmap <F8> :TagbarToggle<CR>
map <C-n> :NERDTreeToggle<CR>

" use Grep to search string
" grep -nR "something"

syntax on
" set background=dark
" colorscheme solarized

set cursorline
set tabstop=4
"
""always uses spaces instead of tab characters
set expandtab
" size of an "indent"
set shiftwidth=4

"" 
set encoding=utf-8

" set tags=; cs add in the .vimlocal file of project root
silent! so .vimlocal

""set hi Search cterm=NONE ctermfg=white ctermbg=blue
hi Search ctermfg=grey ctermbg=black

" file template
" see https://shapeshed.com/vim-templates/ for more info
" also http://vim.wikia.com/wiki/Auto_commands_for_C/C%2B%2B_editing
if has("autocmd")
  augroup templates
    autocmd BufNewFile *.sh 0r ~/configurations/vim/templates/skeleton.sh |ks|call Created()|'s
    autocmd BufWritePre,FileWritePre *.sh   ks|call LastMod()|'s

    autocmd BufNewFile *.cc 0r ~/configurations/vim/templates/skeleton.c |ks|call Created()|'s
    autocmd BufWritePre,FileWritePre *.cc   ks|call LastMod()|'s

    autocmd BufNewFile *.c 0r ~/configurations/vim/templates/skeleton.c |ks|call Created()|'s
    autocmd BufWritePre,FileWritePre *.h   ks|call LastMod()|'s

    autocmd BufNewFile *.h 0r ~/configurations/vim/templates/skeleton.c |ks|call Created() |call append(line('$'), IncludeGuard())|'s
    autocmd BufWritePre,FileWritePre *.c   ks|call LastMod()|'s

    autocmd BufNewFile CHANGELOG* 0r ~/configurations/vim/templates/skeleton.CHANGELOG.md |ks|'s
   "  autocmd BufReadPost,BufNewFile  CHANGELOG* ks|call append(8, NewLog())|'s

	function! NewLog()
	   let lines = []
	   let lines += [""]
	   let lines += ["##" . strftime("%Y %b %d")]
       let lines += ["[TODO]:"]
       let lines += ["\t1. sth missing"]
       let lines += ["[changed]:"]
       let lines += ["\t2. sth changed"]
       let lines += ["[added]:"]
       let lines += ["\t3. sth added"]
	   return lines
	endfunction
	function! FileName()
	   return expand('%:t')
	endfunction
	function! HeadName()
	   return toupper(substitute(FileName(), '\.', "_", "g"))
	endfunction
	function! IncludeGuard()
	   let lines = []
	   let lines +=  ["#ifndef " . HeadName() . "_"]
	   let lines +=  ["#define " . HeadName() . "_"]
	   let lines +=  [""]
	   let lines +=  ["#endif"]
	   return lines
	endfunction
"autocmd BufNewFile *.h  call append(0, IncludeGuard())

  fun Created()
    if line("$") > 20
      let l = 20
    else
      let l = line("$")
    endif
    exe "1," . l . "g/First created: /s/First created: .*/First created: " .
    \ strftime("%Y %b %d")
  endfun


  " change the last time modified
  fun LastMod()
    if line("$") > 20
      let l = 20
    else
      let l = line("$")
    endif
    exe "1," . l . "g/Last modified: /s/Last modified: .*/Last modified: " .
    \ strftime("%Y %b %d")
  endfun
  augroup END
endif


augroup resCur
	autocmd!
        autocmd BufReadPost * call setpos(".", getpos("'\""))
augroup END




